name: Playwright Tests
on:
  repository_dispatch:
    types: [trigger-playwright-tests]
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_run:
    workflows: ["New build"]
    types:
      - completed
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: bash -c "npm ci"
      - name: Install tests
        run: bash -c "npx @playwright/test install"
      # - name: Install playwright browsers
      #   run: npx playwright install --with-deps
      - name: Run tests
        run: bash -c "npx playwright test"
        continue-on-error: true
      # - run: docker build . --file Dockerfile.focal -t testimage
      # - run: docker run -d --name testconatainer testimage
      # - run: sudo docker cp testconatainer:./tests/playwright-report playwright-report
      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

#           RUN npm install
# RUN npx @playwright/test install
# RUN npx playwright install-deps
# RUN npx playwright test || true
        
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 18
#     - name: Install dependencies
