name: Playwright Tests
on:
  repository_dispatch:
    types: [trigger-playwright-tests]
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_run:
    workflows: ["New build"]
    types:
      - completed
env:
  CI: true

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      # - name: Install dependencies
      #   run: npm ci
      # - name: Install playwright browsers
      #   run: npx playwright install --with-deps
      # - name: Run tests
      #   run: npx playwright test
      - run: docker build . --file Dockerfile.focal -t testimage
      - run: docker run -d --name testconatainer testimage
      - run: sudo docker cp testconatainer:./tests/playwright-report playwright-report
      - name: Save report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: /artifacts
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 18
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#     - uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
